version: '3.8'

services:
  # uptime-kuma:
  #   image: louislam/uptime-kuma:1
  #   container_name: uptime-kuma
  #   restart: always
  #   ports:
  #     - "3077:3001"
  #   volumes:
  #     - uptime-kuma:/app/data

  # grafana:
  #   image: grafana/grafana-oss
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"

  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/local-config.yaml

# volumes:
#   uptime-kuma:


  
