global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      # - targets: ["192.168.1.88:8000"]
      - targets: ["192.168.49.1:8000"]
      # - targets: ["203.202.247.121:8000"]
